name: Check commit name

on:
  push:
    branches: [main, master, rewrite]

jobs:
  main:
    if: startsWith(github.event.head_commit.message, 'Update ')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Create commit comment
      uses: peter-evans/commit-comment@v1
      with:
        body: |
          Hey, please **don't** use generic commit messages, such as "Update file.ext" in your commit messages, otherwise they will be removed from the repository. Always try to explain what you changed within the commit message. Thank you!
    - name: Reset commit
      run: |
        git reset --hard HEAD^
    - name: Force-push commit
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        branch: ${{ github.ref }}
